baseURL = "https://bagombo.org/"
languageCode = "en-us"
title = "Tyler Rhodes Online"

googleAnalytics = "UA-116483631-1"

pygmentsCodeFences = true
pygmentsStyle = "emacs"

[taxonomies]
tag = "tags"
series = "series"

[params.info]
Description = "Tyler Rhodes Online"
Author = "Tyler Rhodes"
TwitterHandle = "@itcheeze"
Image = "mypic.jpg"
